/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditEvents {
  action: string;
  actor_user_id: Int8 | null;
  created_at: Generated<Timestamp>;
  entity_id: Int8 | null;
  entity_type: string;
  id: Generated<Int8>;
  payload: Generated<Json>;
  source: string | null;
}

export interface AuthRoles {
  code: string;
  display_name: string;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  token_hash: string;
  user_id: Int8;
}

export interface AuthUserAccounts {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  password_hash: string | null;
  role_code: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface CoordinationTaskHistory {
  change_reason: string | null;
  changed_by_user_id: Int8 | null;
  created_at: Generated<Timestamp>;
  from_status: string | null;
  id: Generated<Int8>;
  progress_percent: Generated<number>;
  task_id: Int8;
  to_status: string;
}

export interface CoordinationTasks {
  assigned_date: Generated<Timestamp>;
  assigned_employee_id: Int8 | null;
  completion_evidence: string | null;
  coordinator_name: string | null;
  created_at: Generated<Timestamp>;
  due_date: Timestamp | null;
  id: Generated<Int8>;
  notes: string | null;
  priority: Generated<string>;
  progress_percent: Generated<number>;
  requesting_agency: string;
  status: Generated<string>;
  task_category: string;
  task_code: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface CoreEnterprises {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  legal_name: string;
  normalized_name: string;
  tax_code: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CoreIndustrialParks {
  code: string;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  name: string;
}

export interface CoreOrganizationalUnits {
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  name: string;
  parent_id: Int8 | null;
}

export interface CoreSchemaMigrations {
  applied_at: Generated<Timestamp | null>;
  filename: string;
  id: Generated<number>;
}

export interface EnvironmentalPdfDocuments {
  confidence_score: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  enterprise_name: string;
  extracted_waste_kg: Numeric | null;
  extracted_wastewater_m3: Numeric | null;
  file_name: string;
  id: Generated<Int8>;
  is_scanned: Generated<boolean>;
  notes: string | null;
  page_reference: string | null;
  park_name: string;
  reporting_period: string;
  sha256: string;
  status: Generated<string>;
  verified_at: Timestamp | null;
  verified_by_user_id: Int8 | null;
}

export interface EnvironmentalWasteRecords {
  created_at: Generated<Timestamp>;
  enterprise_id: Int8;
  id: Generated<Int8>;
  industrial_park_id: Int8;
  notes: string | null;
  raw_waste_unit: Generated<string>;
  raw_waste_value: Numeric | null;
  raw_wastewater_unit: Generated<string>;
  raw_wastewater_value: Numeric | null;
  reporting_quarter: number | null;
  reporting_year: number;
  solid_waste_kg: Generated<Numeric>;
  source_type: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  wastewater_m3: Generated<Numeric>;
}

export interface FinanceAnnualCharges {
  amount_due: Numeric;
  category_code: string;
  currency_code: Generated<string>;
  id: Generated<Int8>;
  snapshot_id: Int8;
}

export interface FinanceAnnualLeaseSnapshots {
  created_at: Generated<Timestamp>;
  enterprise_id: Int8;
  id: Generated<Int8>;
  industrial_park_id: Int8;
  land_area_m2: Numeric;
  lease_status: string | null;
  lot_location: string;
  reporting_year: number;
  source_file: string;
  source_payload: Generated<Json>;
  source_row: number;
  source_sheet: string;
  source_total_amount: Numeric | null;
  source_total_basis: Generated<string>;
}

export interface FinanceFinancialAdjustments {
  adjustment_type: string;
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by_user_id: Int8 | null;
  id: Generated<Int8>;
  invoice_line_id: Int8;
  reason: string;
  source_file: string | null;
  source_row: number | null;
}

export interface FinanceInvoiceLineBalances {
  amount_adjusted: Numeric | null;
  amount_due: Numeric | null;
  amount_outstanding: Numeric | null;
  amount_paid: Numeric | null;
  category_code: string | null;
  enterprise_id: Int8 | null;
  invoice_id: Int8 | null;
  invoice_line_id: Int8 | null;
}

export interface FinanceInvoiceLines {
  amount: Numeric;
  category_code: string;
  description: string | null;
  id: Generated<Int8>;
  invoice_id: Int8;
}

export interface FinanceInvoices {
  created_at: Generated<Timestamp>;
  due_on: Timestamp | null;
  enterprise_id: Int8;
  id: Generated<Int8>;
  invoice_number: string;
  invoice_series: string | null;
  issued_on: Timestamp | null;
  source_file: string | null;
  source_payload: Generated<Json>;
  source_row: number | null;
  status: Generated<string>;
  total_amount: Numeric;
}

export interface FinancePaymentAllocations {
  amount: Numeric;
  invoice_line_id: Int8;
  payment_id: Int8;
}

export interface FinancePayments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  enterprise_id: Int8;
  id: Generated<Int8>;
  paid_on: Timestamp;
  payment_reference: string | null;
  source_file: string | null;
  source_payload: Generated<Json>;
  source_row: number | null;
}

export interface FinanceServiceCategories {
  code: string;
  display_name: string;
  is_active: Generated<boolean>;
}

export interface InfrastructureAssetCategories {
  code: string;
  description: string | null;
  display_name: string;
  icon_name: string | null;
}

export interface InfrastructureAssets {
  asset_code: string;
  asset_name: string;
  category_code: string;
  commissioning_year: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  industrial_park_id: Int8;
  location_desc: string;
  managing_unit: Generated<string>;
  specs: Generated<Json>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface InfrastructureHandovers {
  asset_id: Int8;
  condition_summary: string;
  created_at: Generated<Timestamp>;
  deliverer: string;
  document_ref: string | null;
  handover_code: string;
  handover_date: Timestamp;
  id: Generated<Int8>;
  notes: string | null;
  receiver: string;
}

export interface InfrastructureProjects {
  actual_cost: Generated<Numeric>;
  completion_date: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_milestone: string;
  estimated_budget: Generated<Numeric>;
  id: Generated<Int8>;
  industrial_park_id: Int8;
  notes: string | null;
  project_code: string;
  project_name: string;
  project_type: string;
  start_date: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface IngestImportBatches {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  import_kind: string;
  imported_by_user_id: Int8 | null;
  source_file: string;
  source_sha256: string;
  status: string;
}

export interface IngestImportRows {
  batch_id: Int8;
  error_message: string | null;
  id: Generated<Int8>;
  raw_payload: Generated<Json>;
  source_row: number | null;
  source_sheet: string | null;
  status: string;
}

export interface MaintenanceFieldReports {
  category: Generated<string>;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  industrial_park_id: Int8;
  linked_incident_id: Int8 | null;
  linked_work_order_id: Int8 | null;
  location_detail: string;
  notes: string | null;
  raw_reporter_name: string | null;
  report_code: string;
  reported_at: Generated<Timestamp>;
  reporter_name: Generated<string>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  severity: Generated<string>;
  source: Generated<string>;
  source_fingerprint: string;
  source_message_key: string | null;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface MaintenanceIncidents {
  asset_id: Int8 | null;
  assigned_to: string | null;
  created_at: Generated<Timestamp>;
  current_status: Generated<string>;
  id: Generated<Int8>;
  incident_code: string;
  industrial_park_id: Int8;
  location_detail: string;
  mitigation_actions: string | null;
  reported_at: Generated<Timestamp>;
  resolved_at: Timestamp | null;
  root_cause: string | null;
  severity: Generated<string>;
  target_resolution_at: Timestamp | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface MaintenanceInspections {
  asset_id: Int8;
  condition_rating: string;
  created_at: Generated<Timestamp>;
  defects_found: string | null;
  evidence_url: string | null;
  id: Generated<Int8>;
  inspected_at: Timestamp;
  inspection_code: string;
  inspector_name: string;
  recommendations: string | null;
}

export interface MaintenanceWorkOrders {
  actual_cost: Generated<Numeric>;
  asset_id: Int8;
  assigned_to: string;
  completed_at: Timestamp | null;
  completion_evidence: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  incident_id: Int8 | null;
  notes: string | null;
  order_code: string;
  order_type: string;
  priority: Generated<string>;
  scheduled_end: Timestamp;
  scheduled_start: Timestamp;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface MonitoringCorrections {
  corrected_value: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: Int8 | null;
  id: Generated<Int8>;
  observation_id: Int8;
  reason: string;
}

export interface MonitoringDevices {
  display_name: string | null;
  external_code: string;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  provider: Generated<string>;
  station_id: Int8;
}

export interface MonitoringObservations {
  created_at: Generated<Timestamp>;
  device_id: Int8;
  id: Generated<Int8>;
  measured_at: Timestamp;
  parameter_id: Int8;
  provider_record_key: string | null;
  quality_code: string | null;
  raw_payload: Generated<Json>;
  value: Numeric | null;
}

export interface MonitoringParameters {
  code: string;
  display_name: string;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  unit: string | null;
}

export interface MonitoringProviderRawPayloads {
  id: Generated<Int8>;
  payload: Json;
  payload_hash: string;
  received_at: Generated<Timestamp>;
  sync_run_id: Int8;
}

export interface MonitoringStations {
  code: string;
  id: Generated<Int8>;
  industrial_park_id: Int8 | null;
  is_active: Generated<boolean>;
  name: string;
}

export interface MonitoringSyncRuns {
  checkpoint: string | null;
  error_message: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  provider: Generated<string>;
  records_received: Generated<number>;
  records_saved: Generated<number>;
  started_at: Generated<Timestamp>;
  status: string;
}

export interface WorkforceEmployeeDuties {
  description: string | null;
  duty_name: string;
  employee_id: Int8;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  source: string | null;
}

export interface WorkforceEmployees {
  birth_date: Timestamp | null;
  created_at: Generated<Timestamp>;
  decision_number: string | null;
  employee_code: string | null;
  employment_type: string | null;
  foreign_language: string | null;
  full_name: string;
  id: Generated<Int8>;
  industrial_park_id: Int8 | null;
  informatics: string | null;
  is_active: Generated<boolean>;
  notes: string | null;
  organizational_unit_id: Int8 | null;
  party_position: string | null;
  political_theory: string | null;
  professional_qualification: string | null;
  source_file: string | null;
  source_payload: Generated<Json>;
  source_row: number | null;
  source_sheet: string | null;
  state_management: string | null;
  team_name: string | null;
  updated_at: Generated<Timestamp>;
  work_position: string | null;
}

export interface WorkforceTaskAssignees {
  employee_id: Int8;
  task_id: Int8;
}

export interface WorkforceTasks {
  assigned_by_user_id: Int8 | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  due_at: Timestamp | null;
  id: Generated<Int8>;
  priority: Generated<string>;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface WorkforceTaskStatusHistory {
  changed_by_user_id: Int8 | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  new_status: string;
  note: string | null;
  old_status: string | null;
  task_id: Int8;
}

export interface DB {
  "audit.events": AuditEvents;
  "auth.roles": AuthRoles;
  "auth.sessions": AuthSessions;
  "auth.user_accounts": AuthUserAccounts;
  "coordination.task_history": CoordinationTaskHistory;
  "coordination.tasks": CoordinationTasks;
  "core.enterprises": CoreEnterprises;
  "core.industrial_parks": CoreIndustrialParks;
  "core.organizational_units": CoreOrganizationalUnits;
  "core.schema_migrations": CoreSchemaMigrations;
  "environmental.pdf_documents": EnvironmentalPdfDocuments;
  "environmental.waste_records": EnvironmentalWasteRecords;
  "finance.annual_charges": FinanceAnnualCharges;
  "finance.annual_lease_snapshots": FinanceAnnualLeaseSnapshots;
  "finance.financial_adjustments": FinanceFinancialAdjustments;
  "finance.invoice_line_balances": FinanceInvoiceLineBalances;
  "finance.invoice_lines": FinanceInvoiceLines;
  "finance.invoices": FinanceInvoices;
  "finance.payment_allocations": FinancePaymentAllocations;
  "finance.payments": FinancePayments;
  "finance.service_categories": FinanceServiceCategories;
  "infrastructure.asset_categories": InfrastructureAssetCategories;
  "infrastructure.assets": InfrastructureAssets;
  "infrastructure.handovers": InfrastructureHandovers;
  "infrastructure.projects": InfrastructureProjects;
  "ingest.import_batches": IngestImportBatches;
  "ingest.import_rows": IngestImportRows;
  "maintenance.field_reports": MaintenanceFieldReports;
  "maintenance.incidents": MaintenanceIncidents;
  "maintenance.inspections": MaintenanceInspections;
  "maintenance.work_orders": MaintenanceWorkOrders;
  "monitoring.corrections": MonitoringCorrections;
  "monitoring.devices": MonitoringDevices;
  "monitoring.observations": MonitoringObservations;
  "monitoring.parameters": MonitoringParameters;
  "monitoring.provider_raw_payloads": MonitoringProviderRawPayloads;
  "monitoring.stations": MonitoringStations;
  "monitoring.sync_runs": MonitoringSyncRuns;
  "workforce.employee_duties": WorkforceEmployeeDuties;
  "workforce.employees": WorkforceEmployees;
  "workforce.task_assignees": WorkforceTaskAssignees;
  "workforce.task_status_history": WorkforceTaskStatusHistory;
  "workforce.tasks": WorkforceTasks;
}
